
export const CART_ADD_PRODUCT_REQUEST = 'CART_ADD_PRODUCT_REQUEST'
export const CART_ADD_PRODUCT_SUCCESS = 'CART_ADD_PRODUCT_SUCCESS'
export const CART_ADD_PRODUCT_FAIL = 'CART_ADD_PRODUCT_FAIL'

export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST'
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'
export const FETCH_CART_FAIL = 'FETCH_CART_FAIL'

export const REMOVE_ITEM_REQUEST = 'REMOVE_ITEM_REQUEST'
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS'
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL'

export const ANONYMOUS_CART_ADD_PRODUCT_REQUEST = 'CART_ADD_PRODUCT_REQUEST'
export const ANONYMOUS_ADD_PRODUCT_SUCCESS = 'CART_ADD_PRODUCT_SUCCESS'
export const ANONYMOUS_ADD_PRODUCT_FAIL = 'CART_ADD_PRODUCT_FAIL'