
export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

export const PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST'
export const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS'
export const PAY_ORDER_FAIL = 'PAY_ORDER_FAIL'

export const MARK_DELIVERED_REQUEST = 'MARK_DELIVERED_REQUEST'
export const MARK_DELIVERED_SUCCESS = 'MARK_DELIVERED_SUCCESS'
export const MARK_DELIVERED_FAIL = 'MARK_DELIVERED_FAIL'

export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST'
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL'

export const FETCH_ALL_ORDERS_REQUEST = 'FETCH_ALL_ORDERS_REQUEST'
export const FETCH_ALL_ORDERS_SUCCESS = 'FETCH_ALL_ORDERS_SUCCESS'
export const FETCH_ALL_ORDERS_FAIL = 'FETCH_ALL_ORDERS_FAIL'

export const FETCH_MY_ORDERS_REQUEST = 'FETCH_MY_ORDERS_REQUEST'
export const FETCH_MY_ORDERS_SUCCESS = 'FETCH_MY_ORDERS_SUCCESS'
export const FETCH_MY_ORDERS_FAIL = 'FETCH_MY_ORDERS_FAIL'