
export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST'
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS'
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL'

export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'

export const PRODUCT_INFORMATION_REQUEST = 'PRODUCT_INFORMATION_REQUEST'
export const PRODUCT_INFORMATION_SUCCESS = 'PRODUCT_INFORMATION_SUCCESS'
export const PRODUCT_INFORMATION_FAIL = 'PRODUCT_INFORMATION_FAIL'

export const PRODUCT_REVIEWS_REQUEST = 'PRODUCT_REVIEWS_REQUEST'
export const PRODUCT_REVIEWS_SUCCESS = 'PRODUCT_REVIEWS_SUCCESS'
export const PRODUCT_REVIEWS_FAIL = 'PRODUCT_REVIEWS_FAIL'

export const CREATE_PRODUCT_REVIEW_REQUEST = 'CREATE_PRODUCT_REVIEW_REQUEST'
export const CREATE_PRODUCT_REVIEW_SUCCESS = 'CREATE_PRODUCT_REVIEW_SUCCESS'
export const CREATE_PRODUCT_REVIEW_FAIL = 'CREATE_PRODUCT_REVIEW_FAIL'

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL'

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL'

export const UPLOAD_PRODUCT_IMAGE_REQUEST = 'TUPLOAD_PRODUCT_IMAGE_REQUEST'
export const UPLOAD_PRODUCT_IMAGE_SUCCESS = 'UPLOAD_PRODUCT_IMAGE_SUCCESS'
export const UPLOAD_PRODUCT_IMAGE_FAIL = 'UPLOAD_PRODUCT_IMAGE_FAIL'

export const SIMILAR_PRODUCT_REQUEST = 'SIMILAR_PRODUCT_REQUEST'
export const SIMILAR_PRODUCT_SUCCESS = 'SIMILAR_PRODUCT_SUCCESS'
export const SIMILAR_PRODUCT_FAIL = 'SIMILAR_PRODUCT_FAIL'

export const TOP_PRODUCTS_REQUEST = 'TOP_PRODUCTS_REQUEST'
export const TOP_PRODUCTS_SUCCESS = 'TOP_PRODUCTS_SUCCESS'
export const TOP_PRODUCTS_FAIL = 'TOP_PRODUCTS_FAIL'