
export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST'
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS'
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL'

export const PRODUCT_INFORMATION_REQUEST = 'PRODUCT_INFORMATION_REQUEST'
export const PRODUCT_INFORMATION_SUCCESS = 'PRODUCT_INFORMATION_SUCCESS'
export const PRODUCT_INFORMATION_FAIL = 'PRODUCT_INFORMATION_FAIL'

export const PRODUCT_REVIEWS_REQUEST = 'PRODUCT_REVIEWS_REQUEST'
export const PRODUCT_REVIEWS_SUCCESS = 'PRODUCT_REVIEWS_SUCCESS'
export const PRODUCT_REVIEWS_FAIL = 'PRODUCT_REVIEWS_FAIL'

export const CREATE_PRODUCT_REVIEW_REQUEST = 'CREATE_PRODUCT_REVIEW_REQUEST'
export const CREATE_PRODUCT_REVIEW_SUCCESS = 'CREATE_PRODUCT_REVIEW_SUCCESS'
export const CREATE_PRODUCT_REVIEW_FAIL = 'CREATE_PRODUCT_REVIEW_FAIL'