
export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST'
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS'
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL'

export const SAVE_SHIPPING_REQUEST = 'SAVE_SHIPPING_REQUEST'
export const SAVE_SHIPPING_SUCCESS = 'SAVE_SHIPPING_SUCCESS'
export const SAVE_SHIPPING_FAIL = 'SAVE_SHIPPING_FAIL'

export const FETCH_SHIPPING_REQUEST = 'FETCH_SHIPPING_EQUEST'
export const FETCH_SHIPPING_SUCCESS = 'FETCH_SHIPPING_SUCCESS'
export const FETCH_SHIPPING_FAIL = 'FETCH_SHIPPING_FAIL'